name: 'master'
on:
  push:
    branches: [ master ]

    runs-on: ubuntu-latest
    name: Build & Test Microservice
    steps:
      - name: master
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Cache Maven packages / tr4200812
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "sonatype-nexus-snapshots",
              "username": "${{ secrets.OSS_USERNAME }}",
              "password": "${{ secrets.OSS_PASSWORD }}"
            }]
      - name: Build
        run: >
          ./mvnw deploy
          -DsurefireArgs=-Dspring.profiles.active=TEST
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -U -B $MAVEN_OPTS
